on:
    push:
      branches:
        - master
  
name: 🚀 Deploy website on push
  
jobs:
    web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v2
          with:
            path: 'tapShareBackend'  # Specify the path to the backend folder
            ref: 'master'
  
        - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@4.3.2
          with:
            server:  ${{ secrets.ftp_server }}
            username: ${{ secrets.ftp_username }}
            password: ${{ secrets.ftp_password }}
            source: 'tapShareBackend/tapsharebackend' 